# Site settings
title: Donald Livingston
email: hello@donaldlivingston.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Donald Livingston. I'm a Front-End Web Developer, Digital Craftsman, and Technology Enthusiast. This is my website. 
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://donaldlivingston.com" # the base hostname & protocol for your site
twitter_username: Don_Livingston
github_username:  dlivingston

# Build settings
markdown: kramdown
sass:
    style: :compact
